### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by ghost**
Fixed typo.

(Now hopefully without change to end of file.)

### CODE REVIEW

**Comment by sunknudsen** [comment]
Thanks @7aqdxe6f.

Btw, have you stumbled upon https://sunknudsen.com/privacy-guides/docs#how-to-sign-pull-requests?

Signing pull requests on your computer doesn’t require too much work if you have PGP configured (likely in the form of GnuPG)?

**Comment by ghost** [comment]
Yes, I have seen the guide. Already have a key too, but haven't taken the time to upload the key to a key server (I assume this would be a good idea, so that others can verify the commit manually?).

**Comment by ghost** [comment]
Also tried using the web editor so the commit would be verified, but I had some issues where the last line of the file would somehow change even though I did not edit it.

**Comment by sunknudsen** [comment]
> I assume this would be a good idea, so that others can verify the commit manually?

Yes... that said, in the context of GitHub, given public key is added [here](https://github.com/settings/keys), commits are labelled as verified and, if others trust GitHub, I guess it's good enough to get started.

Btw, you can upload your key to openpgp.org using the following (in case you haven’t explored that rabbit hole).

```shell
gpg --keyserver hkps://keys.openpgp.org --send-keys 0xC1323A377DE14C8B
```

Don’t forget to replace `0xC1323A377DE14C8B` with your PGP public key ID.

Thanks again for contributing. 🤓

**Comment by sunknudsen** [comment]
> Also tried using the web editor so the commit would be verified, but I had some issues where the last line of the file would somehow change even though I did not edit it.

I guess GitHub removes trailing line breaks.

**Comment by ghost** [comment]
Thanks for the help, I'll look into it! Maybe for now it would be best for you to make the change (that way it is verified) and close the PR?

**Comment by sunknudsen** [comment]
Interesting... I tend to add trailing line breaks but not in this case... so I agree it is puzzling that GitHub flagged an edit on that last line.

> Maybe for now it would be best for you to make the change (that way it is verified) and close the PR?

I am thankful you are helping keep content free of typos and I don’t mind keeping this PR open while you figure out how to implement Git signing on your computer.

That said, I can also fix the typo at my end. I will leave it up to you to decide.

Btw, instead of creating another issue, I believe you can squash commit and force push to https://github.com/7aqdxe6f/homebrew-tap.

This might be a naive assumption (I am not a Git expert), but it’s likely worth a try.

```shell
git reset --soft 0c56d77f965bb89c022297bbbd9e1428e15283c4
git commit -m "Fixed typo"
git push -f
```

**Comment by ghost** [comment]
Thanks for the info, I did not know that. Sorry for opening a redundant PR.

Since I won't have the time to implement commit signing in the next few days, I think it would be better if you could make the change yourself.

PS: I think I found another typo, but since I won't be able to sign that commit either, I hope you don't mind if I tell you this way: In the new [Privacy Guide](https://github.com/sunknudsen/privacy-guides/tree/master/how-to-install-tails-on-usb-flash-drive-or-sd-card-on-macos) on [line 137](https://github.com/sunknudsen/privacy-guides/blame/master/how-to-install-tails-on-usb-flash-drive-or-sd-card-on-macos/README.md#L137) it should say "rdiskn" instead of "rdisk2".

**Comment by sunknudsen** [comment]
> PS: I think I found another typo, but since I won't be able to sign that commit either, I hope you don't mind if I tell you this way: In the new Privacy Guide on line 137 it should say "rdiskn" instead of "rdisk2".

You sure did, and that typo could have destroyed someone’s data. **Thanks for reporting it.**

You clearly have an eye for this... really appreciate your contributions. 🙌

I’ve [added](https://github.com/sunknudsen/privacy-guides/commit/e8942306e603cb8f419733bb5b59cefb85e06d21) you to contributors of [Tails install](https://sunknudsen.com/privacy-guides/how-to-install-tails-on-usb-flash-drive-or-sd-card-on-macos) guide.

Thanks again!

**Pull request closed without merging**
